#pragma checksum "..\..\AdaugaConsimtamantWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5E379DEC40F10D2DAC7DDDC24676FD897FC93D4CA7D7E46ACEFF9F6DA89E6678"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DentalProApp {
    
    
    /// <summary>
    /// AdaugaConsimtamantWindow
    /// </summary>
    public partial class AdaugaConsimtamantWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbPacienti;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCNP;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTelefon;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbMedici;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDescriere;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\AdaugaConsimtamantWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DentalProApp;component/adaugaconsimtamantwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\AdaugaConsimtamantWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.cmbPacienti = ((System.Windows.Controls.ComboBox)(target));
            
            #line 19 "..\..\AdaugaConsimtamantWindow.xaml"
            this.cmbPacienti.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbPacienti_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.txtCNP = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.txtTelefon = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.cmbMedici = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.txtDescriere = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.dpData = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 7:
            
            #line 39 "..\..\AdaugaConsimtamantWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSalveaza_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

